name: Publish to PyPI

on:
  release:
    types:
      - published
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Build the package
      run: poetry build

    - name: Publish to PyPI
      if: ${{ matrix.python-version == '3.11' }}  # Only publish once for the highest version
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry publish --build
